### ISSUE TITLE
SHARPpy breaks on startup on Windows 10

### ISSUE THREAD

**Issue by Ks0stm** [sharppy/SHARPpy#106]
Get an error message when starting the Windows 10 download of SHARPpy saying SHARPpy broke and giving the following details:

> SHARPpy
 v1.3.0 Xenia
Crash time: 2017-01-24 16:49:47.456000
Traceback (most recent call last):
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\full_gui", line 55, in doCrasher
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\full_gui", line 664, in createWindow
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\full_gui", line 543, in __init__
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\full_gui", line 549, in __initUI
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\full_gui", line 111, in __init__
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\datasources.data_source", line 64, in pingURLs
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\datasources.data_source", line 47, in _pingURL
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 127, in urlopen
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 410, in open
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 523, in http_response
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 442, in error
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 382, in _call_chain
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 629, in http_error_302
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 410, in open
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 523, in http_response
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 442, in error
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 382, in _call_chain
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 629, in http_error_302
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 404, in open
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 422, in _open
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 382, in _call_chain
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 1214, in http_open
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\urllib2", line 1187, in do_open
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\httplib", line 1067, in getresponse
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\httplib", line 409, in begin
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\httplib", line 365, in _read_status
  File "C:\Users\keltonhalbert\SHARPpy-xenia\runsharp\build\SHARPpy-win8-64\out00-PYZ.pyz\socket", line 476, in readline
timeout: timed out

**Comment by tsupinie** [comment]
It looks like you're using one of the binaries. Unfortunately, the workaround right now is to download the Python code and run that; I should have that error fixed in the code. We'll be re-compiling the binaries when we release a new version.

**Comment by Ks0stm** [comment]
Awesome, using the code seems to do the trick. Thanks!

**Comment by tsupinie** [comment]
Excellent!
