### ISSUE TITLE
Open file issue

### ISSUE THREAD

**Issue by SirMarM** [sharppy/SHARPpy#107]
Hello,

Sharppy works fine on my computer for observed and models soundings. But when I try to open a sounding, even from the example file 14061619.OAX, it does not work.

Here is what I get:

SHARPpy v1.3.0 Xenia
Crash time: 2017-02-27 23:14:57.359000
Traceback (most recent call last):
File "C:\Users\Tim\SHARPpy\runsharp\build\SHARPpy-win7-64\out00-PYZ.pyz\full_gui", line 54, in doCrasher
File "C:\Users\Tim\SHARPpy\runsharp\build\SHARPpy-win7-64\out00-PYZ.pyz\full_gui", line 609, in openFile
File "C:\Users\Tim\SHARPpy\runsharp\build\SHARPpy-win7-64\out00-PYZ.pyz\full_gui", line 423, in skewApp
File "C:\Users\Tim\SHARPpy\runsharp\build\SHARPpy-win7-64\out00-PYZ.pyz\full_gui", line 501, in loadArchive
IOError: Could not figure out the format of 'C:\Users\MarM\Desktop\14061619.OAX.txt'!

Anyone has an idea? 
I am running Python 2.7, and Sharppy for Windows 64 bits. Numpy et Pyside 1.2.4 have been installed as indicated.

Thanks,

**Comment by tsupinie** [comment]
Could you try this again with the latest version of the master branch? I pushed some changes that might have fixed this issue. Thanks!
