### ISSUE TITLE
SHARPpy broken on numpy 1.12.1

### ISSUE THREAD

**Issue by stilwellweather** [sharppy/SHARPpy#119]
Hello,

I am unable to load any modeled soundings as of numpy version 1.12.1. When trying to load, SHARPpy displays the following output:

Well, this is embarrassing.
SHARPpy broke. This is probably due to an issue with one of the data source servers, but if it keeps happening, send the detailed information to the developers.

Detailed Information:
SHARPpy v1.3.0 Xenia
Crash time: 2017-05-25 15:04:38.642043
Traceback (most recent call last):
  File "full_gui.py", line 54, in doCrasher
    ret = func(*args, **kwargs)
  File "full_gui.py", line 355, in complete_name
    self.skewApp()
  File "full_gui.py", line 461, in skewApp
    raise exc
TypeError: only integer scalar arrays can be converted to a scalar index

2017-05-25 15:04:47.394 python[41050:159086] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
In the __init__() for custom _Popen
2017-05-25 15:04:51.079 python[41050:159086] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Traceback (most recent call last):
  File "/Users/robertstilwell/miniconda2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/SPCWindow.py", line 694, in addProfileCollection
    self.spc_widget.addProfileCollection(prof_col, menu_name, focus=focus)
  File "/Users/robertstilwell/miniconda2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/SPCWindow.py", line 269, in addProfileCollection
    self.updateProfs()
  File "/Users/robertstilwell/miniconda2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/SPCWindow.py", line 340, in updateProfs
    self.convective.setProf(self.default_prof)
  File "/Users/robertstilwell/miniconda2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/thermo.py", line 200, in setProf
    self.plotData()
  File "/Users/robertstilwell/miniconda2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/thermo.py", line 244, in plotData
    self.drawConvectiveIndices(qp)
  File "/Users/robertstilwell/miniconda2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/thermo.py", line 471, in drawConvectiveIndices
    if text == self.pcl_types[self.skewt_pcl]:
TypeError: only integer scalar arrays can be converted to a scalar index

Just wanted to let the developers know of this issue.

Thank you.

**Comment by tsupinie** [comment]
Hi! I just pushed a few changes to the master branch that should fix problems with Numpy v1.12. Could you let me know if they work?

**Comment by stilwellweather** [comment]
No issues anymore. Thanks for the quick fix!

**Comment by tsupinie** [comment]
Awesome! You're welcome!
