### ISSUE TITLE
GUI Start problems

### ISSUE THREAD

**Issue by kenpryor67** [sharppy/SHARPpy#122]
I successfully downloaded and installed SHARPpy on my Linux computer:
Linux rhw9150.star1.nesdis.noaa.gov 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Installed /data/home002/kpryor/miniconda3/envs/python2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg
Processing dependencies for SHARPpy==1.3.0
Finished processing dependencies for SHARPpy==1.3.0

However, when I attempt to start the GUI, the following errors appear:
(python2) ken.pryor@rhw9150: python full_gui.py
Traceback (most recent call last):
File "full_gui.py", line 25, in 
from sharppy.viz.SPCWindow import SPCWindow
File "/data/home002/kpryor/miniconda3/envs/python2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/init.py", line 1, in 
from skew import plotSkewT
File "/data/home002/kpryor/miniconda3/envs/python2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/skew.py", line 5, in 
from sharppy.viz.barbs import drawBarb
File "/data/home002/kpryor/miniconda3/envs/python2/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/barbs.py", line 2, in 
from PySide import QtGui, QtCore
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory

What other actions might be necessary to start the GUI?

**Comment by wblumberg** [comment]
I'm closing this issue because it seems like we were able to find a way around this Ken!

**Comment by kenpryor67** [comment]
Thanks, Greg! I'll contact you by email to fill you in on my latest developments.
