### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by fifi2961** [sharppy/SHARPpy#123]
Hi,
On OSX Sierra, I get the message at launch full_gui.py:

Traceback (most recent call last):
  File "/Users/philippe/jupyter/meteo/SHARPpy/runsharp/full_gui.py", line 25, in <module>
    from sharppy.viz.SPCWindow import SPCWindow
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/__init__.py", line 1, in <module>
    from skew import plotSkewT
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/skew.py", line 5, in <module>
    from sharppy.viz.barbs import drawBarb
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/viz/barbs.py", line 2, in <module>
    from PySide import QtGui, QtCore
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PySide/QtGui.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PySide/QtGui.so
  Reason: image not found

Anyone can help me?
Thanks,
Philippe

**Comment by wblumberg** [comment]
This might be an issue associated with downloading a working copy of PySide from Anaconda.  Try the command in the latest README and see if that helps!
