### ISSUE TITLE
SHARPpy broken v1.3.0 Xenia

### ISSUE THREAD

**Issue by Vulur** [sharppy/SHARPpy#137]
Hi,

I installed SHARPpy follows the steps in readme.md. When I try to run SHARP broken message appear

Regards,

Luis

_Installed d:\anaconda2\lib\site-packages\sharppy-1.3.0-py2.7.egg
Processing dependencies for SHARPpy==1.3.0
Finished processing dependencies for SHARPpy==1.3.0

(base) D:\Anaconda2\SHARPpy>cd runsharp

(base) D:\Anaconda2\SHARPpy\runsharp>python full_gui.py

Well, this is embarrassing.
SHARPpy broke. This is probably due to an issue with one of the data source servers, but if it keeps happening, send the detailed information to the developers.

Detailed Information:
SHARPpy v1.3.0 Xenia
Crash time: 2018-04-03 14:44:12.503000
Traceback (most recent call last):
  File "full_gui.py", line 54, in doCrasher
    ret = func(*args, **kwargs)
  File "full_gui.py", line 661, in createWindow
    return Main()
  File "full_gui.py", line 537, in __init__
    self.__initUI()
  File "full_gui.py", line 543, in __initUI
    self.picker = Picker(self.config, parent=self)
  File "full_gui.py", line 96, in __init__
    self.data_sources = data_source.loadDataSources()
  File "D:\Anaconda2\lib\site-packages\sharppy-1.3.0-py2.7.egg\datasources\data_source.py", line 39, in loadDataSources
    root = ET.parse(ds_file).getroot()
  File "D:\Anaconda2\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "D:\Anaconda2\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "D:\Anaconda2\lib\xml\etree\ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "D:\Anaconda2\lib\xml\etree\ElementTree.py", line 1523, in _raiseerror
    raise err
ParseError: not well-formed (invalid token): line 4, column 95

(base) D:\Anaconda2\SHARPpy\runsharp>_

**Comment by mitchellkrogza** [comment]
@Vulur I got this working on CentOS7 thanks to @tsupinie Have a look at https://github.com/sharppy/SHARPpy/issues/143
