### ISSUE TITLE
Missing Data for Create_Profile

### ISSUE THREAD

**Issue by aspassiani** [sharppy/SHARPpy#171]
Hi, 

I am having issues defining missing data when creating my profile. I have some levels with no temperature data so I've defined the temperature at those levels to be -9999. and then specified that to be the "missing" value when I go to create that profile. But I receive the following error:

```
Traceback (most recent call last):

  File "<ipython-input-2-631115c426ae>", line 1, in <module>
    runfile('R:/PHDACS-A2116/ERA_Interim/point_analysis_accessCM.py', wdir='R:/PHDACS-A2116/ERA_Interim')

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "R:/PHDACS-A2116/ERA_Interim/point_analysis_accessCM.py", line 125, in <module>
    dwpc=(dewpt[i,:]), wspd=(wspd[i,:]*1.9438444924406), wdir=wdir[i,:], missing=-9999., strictQC=True)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\sharppy\sharptab\profile.py", line 88, in create_profile
    return BasicProfile(**kwargs)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\sharppy\sharptab\profile.py", line 286, in __init__
    super(BasicProfile, self).__init__(**kwargs)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\sharppy\sharptab\profile.py", line 160, in __init__
    self.checkDataIntegrity()

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\sharppy\sharptab\profile.py", line 216, in checkDataIntegrity
    qc_tools.raiseError("Invalid temperature data. Profile contains a temperature value < -273.15 Celsius.", qc_tools.DataQualityException)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\sharppy\io\qc_tools.py", line 30, in raiseError
    raise Exception(errorType, string)

Exception: (<class 'sharppy.io.qc_tools.DataQualityException'>, 'Invalid temperature data. Profile contains a temperature value < -273.15 Celsius.')
```

I create the profile using this line,

```
prof = profile.create_profile(profile='default', pres=press[i,:], hght=z[1:38], tmpc=(ta[i,:]), \
                                        dwpc=(dewpt[i,:]), wspd=(wspd[i,:]*1.9438444924406), wdir=wdir[i,:], missing=-9999., strictQC=True)
```

I'm not sure if others have encountered this problem or if I'm making a simple mistake that I just can't see. I've tried setting the missing data to 'nan' but when I do that I run into the issue of the dimensions of the input arrays not being of equal size. 

Any help with how to deal with missing/bad data within a profile would be greatly appreciated. 

Cheers,
Alessio

**Comment by wblumberg** [comment]
Hi Alessio,

I'm just now getting to addressing this issue.  One of the big things I see is that you're passing tuples into tmpc, dwpc, and wspd in the profile object creation function instead of arrays.  That might be one issue as SHARPpy isn't expecting tuples for those variables.  That might explain your problem with passing input arrays that are not of the same size.  You also probably want to make sure all of the input arrays are 1-D Numpy arrays.  You'll want your arrays to successfully have masked values via this sample code (pulled from profile.py):

> press[i,:][press[i,:] == -9999] = ma.masked

Greg

**Comment by aspassiani** [comment]
Hi Greg,

Thanks for the help. I tried your suggestion, making sure that the inputs are numpy arrays but I still run into the same issues. If I set the bad data to "-9999" it tells me I have temperature values below -273.15, and if I mask those values before inputting them into SHARPpy, it tells me that the dimensions don't match. 

```
Traceback (most recent call last):

  File "<ipython-input-24-631115c426ae>", line 1, in <module>
    runfile('R:/PHDACS-A2116/ERA_Interim/point_analysis_accessCM.py', wdir='R:/PHDACS-A2116/ERA_Interim')

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "R:/PHDACS-A2116/ERA_Interim/point_analysis_accessCM.py", line 140, in <module>
    dwpc= dwpc_tmp, wspd= wspd_tmp, wdir= wdir_tmp, missing=-9999., strictQC=True)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\sharppy\sharptab\profile.py", line 88, in create_profile
    return BasicProfile(**kwargs)

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\sharppy\sharptab\profile.py", line 331, in __init__
    self.vtmp[self.dwpc.mask[idx]] = self.tmpc[self.dwpc.mask[idx]] # Masking any virtual temperature

  File "C:\Users\uqaspass\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\ma\core.py", line 3174, in __getitem__
    dout = self.data[indx]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 37 but corresponding boolean dimension is 35
```

I'm not quite sure what I may be missing, if you have any other suggestions that would be great. Or I may just have python skip those time steps and continue on to the next without doing any calculations. 

Cheers,
Alessio

**Comment by wblumberg** [comment]
Hi Alessio.

I suspect this might be a Numpy versioning problem.  Maybe make sure you're using the latest version of SHARPpy and Numpy above 1.15?

Thanks,

Greg

**Comment by aspassiani** [comment]
Hi Greg, 

Thanks, I think that might have been the issue. Haven't had the error pop up recently.

Cheer!
