### ISSUE TITLE
v1.4.0b1 throws error when clicking Generate Profiles

### ISSUE THREAD

**Issue by dziban303** [sharppy/SHARPpy#181]
W10 x64, Sharppy v1.4.0b1.

No matter what Sounding Source I choose, or which station I select, I get an error when clicking Generate Profiles.

Example error:

`SHARPpy v1.4.0b1 Andover
Crash time: 2019-11-10 14:34:59.208551
Traceback (most recent call last):
  File "runsharp\full_gui.py", line 134, in doCrasher
  File "runsharp\full_gui.py", line 599, in complete_name
  File "datasources\data_source.py", line 375, in getForecastHours
  File "datasources\data_source.py", line 350, in _get
  File "datasources\data_source.py", line 167, in getForecastHours
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

![image](https://user-images.githubusercontent.com/7931765/68550358-b77cb500-03c7-11ea-9444-6e78f2c25a61.png)

**Comment by georgephillips1** [comment]
Yeah.  My issue #180 actually was this problem.  What to do?

Exit SHARPpy.
Remove the .sharppy directory in your user profile directory
Restart SHARPpy

It should work then.  Something in the .sharppy directory from previous versions of sharppy is confusing the new version.

**Comment by dziban303** [comment]
Ah, I see. Yeah, that took care of the issue, thanks.
