### ISSUE TITLE
Failure to start Sharppy from Anaconda terminal

### ISSUE THREAD

**Issue by Malcolm47** [sharppy/SHARPpy#200]
**Describe the bug**
After creating a sharppy-env in Anaconda and running sharppy via the terminal, everything works fine. After this, however, it fails to open. I'm not sure what the point is after which it fails - maybe closing sharppy, closing anaconda, or restarting my computer.

**To Reproduce**
1. I created a new sharppy-env in Anaconda
2. I ran sharppy - it worked
3. This is where I don't remember exactly what I did. I closed sharppy and anaconda, and may have restarted my computer.
4. I opened Anaconda and ran sharppy.
5. I got this error:
```
Traceback (most recent call last):
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\Scripts\sharppy-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\runsharp\full_gui.py", line 1226, in main
    main_win = Main()
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\runsharp\full_gui.py", line 869, in __init__
    self.__initUI()
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\runsharp\full_gui.py", line 875, in __initUI
    self.picker = Picker(self.config, parent=self)
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\runsharp\full_gui.py", line 241, in __init__
    self.__initUI()
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\runsharp\full_gui.py", line 254, in __initUI
    self.view = self.create_map_view()
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\runsharp\full_gui.py", line 361, in create_map_view
    self.data_sources[self.model], self.run, self.async_obj, cfg=self.config)
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\sharppy\viz\map.py", line 348, in __init__
    self.setDataSource(data_source, init_time, init=True)
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\sharppy\viz\map.py", line 377, in setDataSource
    self.setCurrentTime(data_time, init=init)
  File "C:\Users\Malcolm\Anaconda3\envs\sharppy-env\lib\site-packages\sharppy\viz\map.py", line 382, in setCurrentTime
    self.clicked.emit(None)
TypeError: MapWidget.clicked[dict].emit(): argument 1 has unexpected type 'NoneType'
```
I have done these steps twice and the same thing has occurred both times.

**Expected behavior**
I expected sharppy to open normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/60855169/80823543-d73cab00-8baa-11ea-9eb6-e2dda08b52de.png)

**Versioning Information (please complete the following information):**
 - Device: [Dell PC]
 - OS: [Windows 10]
 - SHARPpy Version: [v1.4.0]
 - Dependency Versions: [Unknown, but everything was installed recently and updated]:
 - Screen dimensions [2560 x 1440]:
 - SHARPpy distribution type [conda]: 
 
**

**Comment by wblumberg** [comment]
Hi!  Thanks for putting together a thorough issue report for us.  This looks like an issue that occurs when SHARPpy tries to use the older version of PySide instead of PySide2.  I would recommend you try to download SHARPpy from conda-forge into its own environment.  The latest version from conda-forge should fix this issue.

- Greg

**Comment by Malcolm47** [comment]
Thanks, I updated with conda-forge and it seems to work.
