### ISSUE TITLE
[BUG] Error Loading Data

### ISSUE THREAD

**Issue by rfh128** [sharppy/SHARPpy#201]
I get the same error when trying to load data (observed or forecasting data) after installing sharppy on my macbook. Any ideas what this could be? Thank you

SHARPpy v1.4.0+1.g684d8251 Andover
Crash time: 2020-05-19 14:35:14.392887
Traceback (most recent call last):
  File "runsharp/full_gui.py", line 136, in doCrasher
  File "runsharp/full_gui.py", line 601, in complete_name
  File "datasources/data_source.py", line 375, in getForecastHours
  File "datasources/data_source.py", line 350, in _get
  File "datasources/data_source.py", line 167, in getForecastHours
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by toreal** [comment]
I can run it after install pyside2.
`pip install pyside2`
