### ISSUE TITLE
[BUG] SHARPpy Unable to Display Soundings on Ubuntu 18.04 - Crash in _getOutletWithProfile

### ISSUE THREAD

**Issue by buffaloseven** [sharppy/SHARPpy#242]
Before submitting an issue to Github about SHARPpy, please follow the below checklist to ensure that your issue can be resolved quickly.  

- [X] No other issues either open or closed describe what I'm reporting.
- [X] I have checked to see if my issue has been resolved in a new version of SHARPpy.
- [X] I have filled out the below information in as much detail as possible using dates, numbers, directions, pictures, etc.
- [X] I have checked the SHARPpy documentation to make sure I'm doing things correctly, and my problem doesn't exist between my monitor and chair.
- [X] I have attached the log and config files from the ~/.sharppy folder.  If no log files exist, I have run the program in debug mode (e.g., sharppy --debug).

The management team for SHARPpy is a small team of volunteers.  Being as thorough as possible with your issue submission will help us help you!

SHARPpy is unable to display soundings, fails with the following error (output from running with the `--debug` flag.

```bash
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/wwg/home/[user]/SHARPpy/runsharp/full_gui.py", line 609, in complete_name
    self.skewApp(ntry=n_tries)
  File "/net/wwg/home/[user]/SHARPpy/runsharp/full_gui.py", line 772, in skewApp
    raise exc
  File "/net/local/home/[user]/miniconda3/envs/sharppy/lib/python3.10/site-packages/SHARPpy-1.4.0+12.ge7ffe83e.dirty-py3.10.egg/sutils/async_threads.py", line 122, in run
    ret_val = func(*args, **kwargs)
  File "/net/wwg/home/[user]/SHARPpy/runsharp/full_gui.py", line 836, in loadData
    decoder, url = data_source.getDecoderAndURL(loc, run, outlet_num=ntry)
  File "/net/local/home/[user]/miniconda3/envs/sharppy/lib/python3.10/site-packages/SHARPpy-1.4.0+12.ge7ffe83e.dirty-py3.10.egg/datasources/data_source.py", line 436, in getDecoderAndURL
    outlet = self._getOutletWithProfile(stn, cycle_dt, outlet_num=outlet_num)
  File "/net/local/home/[user]/miniconda3/envs/sharppy/lib/python3.10/site-packages/SHARPpy-1.4.0+12.ge7ffe83e.dirty-py3.10.egg/datasources/data_source.py", line 367, in _getOutletWithProfile
    raise DataSourceError()
datasources.data_source.DataSourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/net/wwg/home/[user]/SHARPpy/runsharp/full_gui.py", line 137, in doCrasher
    ret = func(*args, **kwargs)
  File "/net/wwg/home/[user]/SHARPpy/runsharp/full_gui.py", line 615, in complete_name
    raise IOError(
OSError: No outlet found with the requested profile!
Exception: No outlet found with the requested profile!

Well, this is embarrassing.
SHARPpy broke. This is probably due to an issue with one of the data source servers, but if it keeps happening, send the detailed information to the developers.

Detailed Information:
SHARPpy v1.4.0+12.ge7ffe83e.dirty Andover
Crash time: 2022-11-01 14:12:12.062775
Traceback (most recent call last):
  File "/net/local/home/[user]/miniconda3/envs/sharppy/lib/python3.10/site-packages/SHARPpy-1.4.0+12.ge7ffe83e.dirty-py3.10.egg/datasources/data_source.py", line 365, in _getOutletWithProfile
    outlet = use_outlets[outlet_num]
IndexError: list index out of range
```

**To Reproduce**
1. Launch SHARPpy (either via `sharppy` or `python full_gui.py`
2. Load any sounding.
3. Generate Profiles

**Expected behavior**
The profile would be correctly generated and displayed.

**Versioning Information (please complete the following information):**
 - Device: Desktop Workstation
 - OS: Ubuntu 18.04
 - SHARPpy Version: 1.4.0
 - Dependency Versions: As defined in `environment.yml`
 - Screen dimensions: 1920x1200
 - SHARPpy distribution type [e.g., git, conda, binary]: Git or Conda 
 
** 

**Additional context**
Problem occurs after a fresh install of SHARPpy in a new Conda environment. Problem occurs whether installed via `conda-forge` or through a Git clone.

**Comment by wx4stg** [comment]
same issue here with Fedora 38

**Comment by wx4stg** [comment]
This seems to be caused by having too new of a version of pyside2. You can work around this by creating a new conda environment with pyside2 v5.12:

```
conda create -n sharppy
conda activate sharppy
conda install python=3.7
pip install PySide2==5.12.6
pip install git+https://github.com/sharppy/sharppy
```

**Comment by normanr** [comment]
I had a similar issue, but had to use `--ignore-requires-python` and install _newer_ versions of `PySide2` and `shiboken2`, otherwise pip wanted to install very old versions (because newer versions didn't say that they were compatible with Python 3.11) which didn't work correctly.
