### ISSUE TITLE
[BUG] Cannot Generate Profiles 

### ISSUE THREAD

**Issue by mekkelley** [sharppy/SHARPpy#256]
When I select my model, location, and timestamp, and click 'Generate Profiles', the error below occurs. How can I get past this?

OOPS: PySide2.QtGui.QFont.__init__(): unsupported keyword 'bold'
There was an exception:
Exception: No outlet found with the requested profile!

Well, this is embarrassing.
SHARPpy broke. This is probably due to an issue with one of the data source servers, but if it keeps happening, send the detailed information to the developers.

Detailed Information:
SHARPpy v1.4.0 Andover
Crash time: 2024-06-10 20:06:20.117620
Traceback (most recent call last):
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\datasources\data_source.py", line 365, in _getOutletWithProfile
    outlet = use_outlets[outlet_num]
             ~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 608, in complete_name
    self.skewApp(ntry=n_tries)
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 771, in skewApp
    raise exc
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\sutils\async_threads.py", line 122, in run
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 835, in loadData
    decoder, url = data_source.getDecoderAndURL(loc, run, outlet_num=ntry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\datasources\data_source.py", line 436, in getDecoderAndURL
    outlet = self._getOutletWithProfile(stn, cycle_dt, outlet_num=outlet_num)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\datasources\data_source.py", line 367, in _getOutletWithProfile
    raise DataSourceError()
datasources.data_source.DataSourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 136, in doCrasher
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 614, in complete_name
    raise IOError(
OSError: No outlet found with the requested profile!

**Comment by collin-volk** [comment]
Issue #254 should have the information for fixing the no outlets problem, although the font portion is new so there might be something else going on as well.

**Comment by mekkelley** [comment]
Thank you, @collin-volk. I have tried downloading the zip file for the latest release of sharppy and installing the libraries through "conda env create -f environment.yml", and changing the numpy version in the environment file to numpy=1.22.3. 

But it still gives me this error when I use the HRRR model:
C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\sharppy\sharptab\thermo.py:86: RuntimeWarning: divide by zero encountered in true_divide
  return 1000. / (np.power((theta / t),(1./ROCP)))
C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\numpy\lib\function_base.py:1570: UserWarning: Warning: converting a masked element to nan.
  return interp_func(x, xp, fp, left, right)
C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\sharppy\sharptab\thermo.py:107: RuntimeWarning: invalid value encountered in power
  return ((t + ZEROCNK) * np.power((p2 / p),ROCP)) - ZEROCNK
OOPS: PySide2.QtGui.QFont.__init__(): unsupported keyword 'bold'
There was an exception:
Exception: No outlet found with the requested profile!

Well, this is embarrassing.
SHARPpy broke. This is probably due to an issue with one of the data source servers, but if it keeps happening, send the detailed information to the developers.

Detailed Information:
SHARPpy v1.4.0 Andover
Crash time: 2024-06-11 07:39:56.727572
Traceback (most recent call last):
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\datasources\data_source.py", line 365, in _getOutletWithProfile
    outlet = use_outlets[outlet_num]
             ~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 608, in complete_name
    self.skewApp(ntry=n_tries)
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 771, in skewApp
    raise exc
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\sutils\async_threads.py", line 122, in run
    ret_val = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 835, in loadData
    decoder, url = data_source.getDecoderAndURL(loc, run, outlet_num=ntry)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\datasources\data_source.py", line 436, in getDecoderAndURL
    outlet = self._getOutletWithProfile(stn, cycle_dt, outlet_num=outlet_num)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\datasources\data_source.py", line 367, in _getOutletWithProfile
    raise DataSourceError()
datasources.data_source.DataSourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 136, in doCrasher
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mekke\anaconda3\envs\devel\Lib\site-packages\sharppy-1.4.0-py3.11.egg\runsharp\full_gui.py", line 614, in complete_name
    raise IOError(
OSError: No outlet found with the requested profile!

**Comment by mekkelley** [comment]
Okay I just got it working! I had to play around a lot with the versions of numpy, pyside2, and python in the environment.yml file, and this is what worked for me:

dependencies:
  - python>=3
  - numpy=1.15.*
  - pyside2=5.12.*


Thanks, @collin-volk, looks like the problem was what you said it was in that other issue #254. But using numpy=1.22.3 did not work for me. The above worked in the environment.yml file.

**Comment by cmw1229** [comment]
I am having the same issue but nothing listed above has worked. Please see error below.  Does anyone have a SHARPpy environment that is working they can share (for Windows/Anaconda)



`OOPS: PySide2.QtGui.QFont.__init__(): unsupported keyword 'bold'
There was an exception:
Exception: No outlet found with the requested profile!

Well, this is embarrassing.
SHARPpy broke. This is probably due to an issue with one of the data source servers, but if it keeps happening, send the detailed information to the developers.

Detailed Information:
SHARPpy v1.4.0 Andover
Crash time: 2024-07-09 11:39:26.255721
Traceback (most recent call last):
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\datasources\data_source.py", line 365, in _getOutletWithProfile
    outlet = use_outlets[outlet_num]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\runsharp\full_gui.py", line 608, in complete_name
    self.skewApp(ntry=n_tries)
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\runsharp\full_gui.py", line 771, in skewApp
    raise exc
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\sutils\async_threads.py", line 122, in run
    ret_val = func(*args, **kwargs)
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\runsharp\full_gui.py", line 835, in loadData
    decoder, url = data_source.getDecoderAndURL(loc, run, outlet_num=ntry)
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\datasources\data_source.py", line 436, in getDecoderAndURL
    outlet = self._getOutletWithProfile(stn, cycle_dt, outlet_num=outlet_num)
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\datasources\data_source.py", line 367, in _getOutletWithProfile
    raise DataSourceError()
datasources.data_source.DataSourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\runsharp\full_gui.py", line 136, in doCrasher
    ret = func(*args, **kwargs)
  File "C:\Users\chrissy.rogers.tm\.conda\envs\skewT\lib\site-packages\runsharp\full_gui.py", line 615, in complete_name
    "No outlet found with the requested profile!")
OSError: No outlet found with the requested profile!`
