### ISSUE TITLE
Module Error (isclose) Upon Sounding Retrieval (Version 1.3)

### ISSUE THREAD

**Issue by sbinau** [sharppy/SHARPpy#75]
Just did a fresh install of Xenia Version 1.3.  When choosing any sounding (any model, any time) I get an error (below). The sounding viewer appears but none of the data is plotted. I am suspecting something with numpy - I have both numpy and pyside packages installed under site-packages. 

Loading decoder 'buf_decoder'.
Loading decoder 'spc_decoder'.
Loading decoder 'pecan_decoder'.
In the __init__() for custom _Popen
Process Process-1:
Traceback (most recent call last):
  File "C:\Python27\ArcGIS10.1\lib\multiprocessing\process.py", line 258, in _bo
otstrap
    self.run()
  File "C:\Python27\ArcGIS10.1\lib\multiprocessing\process.py", line 114, in run

    self._target(*self._args, **self._kwargs)
  File "C:\Python27\ArcGIS10.1\lib\site-packages\sharppy-1.3.0-py2.7.egg\sharppy
\sharptab\prof_collection.py", line 11, in doCopy
    pipe.put((target_type.copy(prof), idx))
  File "C:\Python27\ArcGIS10.1\lib\site-packages\sharppy-1.3.0-py2.7.egg\sharppy
\sharptab\profile.py", line 153, in copy
    return cls(**new_kwargs)
  File "C:\Python27\ArcGIS10.1\lib\site-packages\sharppy-1.3.0-py2.7.egg\sharppy
\sharptab\profile.py", line 469, in __init__
    self.get_fire()
  File "C:\Python27\ArcGIS10.1\lib\site-packages\sharppy-1.3.0-py2.7.egg\sharppy
\sharptab\profile.py", line 525, in get_fire
    self.pblmaxwind = winds.max_wind(self, lower=0, upper=pbl_h)
  File "C:\Python27\ArcGIS10.1\lib\site-packages\sharppy-1.3.0-py2.7.egg\sharppy
\sharptab\winds.py", line 365, in max_wind
    ind1 = np.where((plower > prof.pres) | (np.isclose(plower, prof.pres)))[0][0]
AttributeError: 'module' object has no attribute 'isclose'

Thanks for any insight/help.

**Comment by sbinau** [comment]
My numpy package was a little outdated. Reinstall with 1.9.2 fixed my issue.

**Comment by tsupinie** [comment]
Glad to hear you got it resolved! Was going to ask which version of Numpy you had. :)
