### ISSUE TITLE
Sharppy won't run after installation.

### ISSUE THREAD

**Issue by 423967mv** [sharppy/SHARPpy#95]
Well, this is embarrassing.
SHARPpy broke. This is probably due to an issue with one of the data source serv
ers, but if it keeps happening, send the detailed information to the developers.

Detailed Information:
SHARPpy v1.3.0 Xenia
Crash time: 2016-06-12 17:02:17.826000
Traceback (most recent call last):
  File "full_gui.py", line 54, in doCrasher
    ret = func(*args, **kwargs)
  File "full_gui.py", line 668, in createWindow
    return Main()
  File "full_gui.py", line 547, in __init__
    self.__initUI()
  File "full_gui.py", line 553, in __initUI
    self.picker = Picker(self.config, parent=self)
  File "full_gui.py", line 96, in __init__
    self.data_sources = data_source.loadDataSources()
  File "C:\Python27\lib\site-packages\sharppy-1.3.0-py2.7.egg\datasources\data_s
ource.py", line 42, in loadDataSources
    ds[name] = DataSource(src)
  File "C:\Python27\lib\site-packages\sharppy-1.3.0-py2.7.egg\datasources\data_s
ource.py", line 244, in __init__
    self._observed = config.get('observed').lower() == "true"
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by nguy** [comment]
Check PR #94 I submitted, it adds a bit of code that should get the package to work.

**Comment by tsupinie** [comment]
I accepted PR #94 a couple days ago. Could you try and see if it works, @423967mv?

**Comment by 423967mv** [comment]
It works now. :) Thanks!

**Comment by 423967mv** [comment]
This is weird, the open functionality didn't work anymore after the first launch.


Detailed Information:
SHARPpy v1.3.0 Xenia
Crash time: 2016-07-17 14:07:14.229000
Traceback (most recent call last):
  File "full_gui.py", line 54, in doCrasher
    ret = func(*args, **kwargs)
  File "full_gui.py", line 597, in openFile
    path = self.config.get('paths', 'load_txt')
  File "C:\Python27\lib\ConfigParser.py", line 340, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'load_txt' in section: 'paths'

**Comment by tsupinie** [comment]
Hey, @423967mv, I just pushed a fix to the master branch. Could you see if it works for you?

**Comment by 423967mv** [comment]
Looks like it works now! :)

**Comment by tsupinie** [comment]
Yay!
